---

- name: Create certificates directory
  file:
    state: directory
    path: "{{ certs_dir }}"
    owner: "{{ current_user }}"
    group: "{{ current_group }}"

- name: Distribute CA to nodes
  copy:
    src: "{{ local_cert_dir }}/{{ ca_cert_name }}"
    dest: "{{ certs_dir }}/{{ ca_cert_name }}"
    mode: '0755'
    owner: "{{ current_user }}"
    group: "{{ current_group }}"

- name: Distribute CA key to nodes
  copy:
    src: "{{ local_cert_dir }}/{{ ca_key_name }}"
    dest: "{{ certs_dir }}/{{ ca_key_name }}"
    mode: '0644'
    owner: "{{ current_user }}"
    group: "{{ current_group }}"