---
- name: Create local cert directory
  local_action:
    module: file
    path: "{{ local_cert_dir }}"
    state: directory
    mode: '0755'

- name: Generate CA key
  local_action:
    module: openssl_privatekey
    path: "{{ local_cert_dir }}/{{ ca_key_name }}"
    size: 2048

- name: Generate CA Self-Signed Certificate
  local_action:
    module: command
    cmd: >
      openssl req -x509 -new -nodes
      -key "{{ local_cert_dir }}/{{ ca_key_name }}"
      -sha256 -days 3650
      -out "{{ local_cert_dir }}/{{ ca_cert_name }}"
      -subj "/C=US/ST=State/L=City/O=Organization/OU=OrgUnit/CN=CommonName"
  args:
    creates: "{{ local_cert_dir }}/{{ ca_cert_name }}"

- name: Distribute CA to nodes
  copy:
    src: "{{ local_cert_dir }}/{{ ca_cert_name }}"
    dest: "{{ certs_dir }}/{{ ca_cert_name }}"
    mode: '0755'
    owner: "{{ current_user }}"
    group: "{{ current_group }}"

- name: Distribute CA key to nodes
  copy:
    src: "{{ local_cert_dir }}/{{ ca_key_name }}"
    dest: "{{ certs_dir }}/{{ ca_key_name }}"
    mode: '0644'
    owner: "{{ current_user }}"
    group: "{{ current_group }}"

- name: Create SAN config from template
  template:
    src: san.cfg.j2
    dest: "{{ certs_dir }}/san.cfg"
    mode: '0644'
    owner: "{{ current_user }}"
    group: "{{ current_group }}"

- name: Generate private key for each node
  openssl_privatekey:
    path: "{{ certs_dir }}/{{ key_name }}"
    size: 2048

- name: Generate CSR for each node
  openssl_csr:
    path: "{{ certs_dir }}/vault-csr.pem"
    privatekey_path: "{{ certs_dir }}/{{ key_name }}"
    common_name: "{{ inventory_hostname }}.{{ base_domain }}"
    subject_alt_name:
      - "DNS: {{ inventory_hostname }}.{{ base_domain }}"
      - "IP:{{ ansible_host | trim }}"
      - "IP:127.0.0.1"

- name: Generate certificates
  openssl_certificate:
    path: "{{ certs_dir }}/{{ cert_name }}"
    csr_path: "{{ certs_dir }}/vault-csr.pem"
    provider: ownca
    ownca_path: "{{ certs_dir }}/{{ ca_cert_name }}"
    ownca_privatekey_path: "{{ certs_dir }}/{{ ca_key_name }}"
    ownca_not_after: "+3650d"
    ownca_create_subject_key_identifier: always_create
    ownca_create_authority_key_identifier: true

- name: Grant privileges to user
  file:
    path: "{{ certs_dir }}"
    mode: '0744'
    owner: "{{ current_user }}"
    group: "{{ current_group }}"
    recurse: true