---
- name: Generate CA
  include_tasks: generate_ca.yml
  when: "{{ generate_ca }} == true"

- name: Distribute CA
  include_tasks: distribute_ca.yml

- name: Generate certs
  include_tasks: generate_certs.yml