---

- name: Start vault service
  service:
    name: vault
    enabled: true
    state: started

- name: Check init status and restart if initialized
  include_tasks: vault_check_status.yaml
  when: raft_backend and not postgres_backend and inventory_hostname in groups['master']

- name: Initialize Vault
  when: inventory_hostname in groups['master']
  command: vault operator init -key-shares=5 -key-threshold=3 -format=json
  register: vault_init_output
  environment:
    VAULT_SKIP_VERIFY: true

- name: Save Vault keys
  copy:
    content: "{{ vault_init_output.stdout | from_json | to_nice_json }}"
    dest: "{{ unseal_keys_path }}"
  when: vault_init_output.changed and inventory_hostname in groups['master']
  delegate_to: localhost
  become: false

- name: Encrypt Vault keys
  command: ansible-vault encrypt {{ unseal_keys_path }}
  when: vault_init_output.changed and inventory_hostname in groups['master']
  delegate_to: localhost
  become: false

- name: Check if Vault is sealed
  command: vault status -format=json
  when: inventory_hostname in groups['master']
  ignore_errors: true
  register: vault_seal_output
  environment:
    VAULT_SKIP_VERIFY: true
    VAULT_ADDR: "https://127.0.0.1:8200"

- name: Unseal vault
  when: vault_seal_output.rc != 0 and inventory_hostname in groups['master']
  include_tasks: unseal_vault.yaml

- name: Unseal vault (workers)
  when: inventory_hostname in groups['workers']
  include_tasks: unseal_vault.yaml
